Introduce gRPC to sockchat
kacperf531/sockchat pull request #10
Opened 2023-05-10 13:30 UTC by kacperf531

2023-05-17 16:14 UTC, wfabjanczuk commented on services/authentication.go
> +	encoded := strings.TrimPrefix(token, "Basic ")
If `token` doesn't start with prefix `Basic `, it is passed to `encoded` unchanged. Is this the desired behavior and base64 encoded `{username}:{password}` should be accepted as well?

If you want to require `Basic ` in the prefix you can use the [strings.CutPrefix](https://pkg.go.dev/strings#CutPrefix) like in the suggestion below or split the `token` by space and validate first part.
```suggestion
	encoded, foundBasic := strings.CutPrefix(token, "Basic ")
	if !foundBasic {
		return nil, api.ErrBasicTokenRequired
	}
```

2023-05-17 16:14 UTC, wfabjanczuk commented on services/authentication.go
> +	return &authWrapper{nick, pwHash}, nil
```suggestion
	credentials := strings.SplitN(string(data), ":", 2)
	if len(credentials) != 2 {
		return nil, api.ErrBasicTokenRequired
	}
	return &authWrapper{credentials[0], credentials[1]}, nil
```
It could be simplified with the [strings.SplitN](https://pkg.go.dev/strings#SplitN)

2023-05-18 09:17 UTC, kacperf531 commented on services/grpc.go
> +			return nil, err
TODO: organize gRPC error codes

2023-05-18 11:40 UTC, wfabjanczuk commented on api/interfaces.go
> +type SockchatWebsocketConnection interface {
optional: one interface without a comment

2023-05-18 11:40 UTC, wfabjanczuk commented on api/serialization.go
> +func UnmarshalMessageEvent(requestBytes json.RawMessage) *MessageEvent {
optional: functions in `api/serialization.go` file have inconsitent signatures; sometimes they return only the struct pointer, sometimes they include the error

2023-05-18 11:40 UTC, wfabjanczuk commented on api/web_messages.go
> +type CreateProfileRequest = struct {
```suggestion
type CreateProfileRequest struct {
```

2023-05-18 11:40 UTC, wfabjanczuk commented on api/ws_messages.go
> +	return NewSocketMessage(InvalidRequestEvent, map[string]string{"details": details})
optional: in `api/web_messages.go` the error response type is defined as a struct instead of a map:
```go
type ErrorResponse struct {
	ErrorDescription string `json:"error_description"`
}
```

2023-05-18 11:40 UTC, wfabjanczuk commented on channel_store.go
>  }
```suggestion
```
GetMembers method is unused

2023-05-18 11:40 UTC, wfabjanczuk commented on protobuf/sockchat.proto
> +message Empty {}
Alternatively you could use
```go
import "google/protobuf/empty.proto";
// ...

service Sockchat {
  rpc RegisterProfile (RegisterProfileRequest) returns (google.protobuf.Empty) {}
  // ...
```

2023-05-18 11:40 UTC, wfabjanczuk commented on services/core.go
> +func (s *SockchatCoreService) GetChannelHistory(req *api.GetChannelHistoryRequest, ctx context.Context) (api.ChannelHistory, error) {
optional: this context is unused while it could be wrapped with timeout and passed down to `MessageStore.runSearchQuery`

2023-05-18 11:40 UTC, wfabjanczuk commented on services/grpc.go
> +	"GetProfile":        true,
```suggestion
var methodAuthorization = map[string]bool{
	"RegisterProfile":   false,
	"GetProfile":        true,
```
optional: you could list all the gRPC methods to explicitly include/exclude authorization for all of them

2023-05-18 11:40 UTC, wfabjanczuk commented on webserver/integration_test.go
> +	services.ServeGRPC(grpcAPI, grpcPort)
```suggestion
```

2023-05-19 13:14 UTC, wfabjanczuk commented on services/grpc.go
> +			return nil, err
Yes please

2023-05-19 14:19 UTC, wfabjanczuk requested changes

2023-05-19 14:19 UTC, wfabjanczuk commented on services/grpc.go
> +var GRPCCodes = map[error]codes.Code{
Please also handle edge case with error not found in the map - zero value for `codes.Code` is `OK Code = 0`.

Error not found in the map is an unexpected internal error that should be logged for developers

2023-05-19 14:24 UTC, wfabjanczuk approved these changes

2023-05-22 11:01 UTC, merged